# Generated by Django 3.2.6 on 2021-08-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210811_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencia',
            name='enderecos',
        ),
        migrations.AddField(
            model_name='referencia',
            name='enderecos',
            field=models.ManyToManyField(to='core.Endereco'),
        ),
    ]
