# Generated by Django 3.2.6 on 2021-08-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210811_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_operacao', models.CharField(blank=True, max_length=15, verbose_name='Nº operação')),
                ('tipo_de_conta', models.CharField(blank=True, max_length=25, verbose_name='Tipo de conta')),
                ('agencia', models.CharField(blank=True, max_length=15, verbose_name='Nº agência')),
                ('conta', models.CharField(blank=True, max_length=15, verbose_name='Nº conta')),
            ],
        ),
    ]
