# Generated by Django 3.2.6 on 2021-08-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dadosbancarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosDaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=50, null=True, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='CNPJ')),
                ('fundacao', models.DateField(blank=True, max_length=8, null=True, verbose_name='Fundação')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal')),
            ],
            options={
                'verbose_name_plural': 'Razão Social',
            },
        ),
    ]
