# Generated by Django 3.2.6 on 2021-08-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dadosdaempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosdaempresa',
            name='razao_social',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Razão '),
        ),
    ]
