# Generated by Django 3.2.6 on 2021-08-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dadosdaempresa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadosdaempresa',
            options={'verbose_name_plural': 'Dados da Empresa '},
        ),
    ]
