# Generated by Django 3.2.6 on 2021-08-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210827_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencia',
            name='enderecos',
        ),
        migrations.AddField(
            model_name='referencia',
            name='enderecos',
            field=models.ManyToManyField(blank=True, max_length=50, to='core.Endereco'),
        ),
    ]
