# Generated by Django 3.2.6 on 2021-08-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210827_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadosdaempresa',
            options={'verbose_name': 'Dados da Empresa ', 'verbose_name_plural': 'Dados das Empresas'},
        ),
    ]
