# Generated by Django 3.2.6 on 2021-08-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_dadosdaempresa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbancarios',
            name='tipo_de_conta',
            field=models.CharField(choices=[('conta corrente', 'January'), ('conta poupança', 'February')], default=' ', max_length=25),
        ),
    ]
