# Generated by Django 3.2.6 on 2021-08-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dadosbancarios_tipo_de_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbancarios',
            name='tipo_de_conta',
            field=models.CharField(choices=[('conta corrente', 'conta corrente'), ('conta poupança', 'conta poupança'), ('conta salário', 'conta salário')], max_length=25),
        ),
    ]
