# Generated by Django 3.2.6 on 2021-08-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_dadosbancarios_tipo_de_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='localDeTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFantasia', models.CharField(max_length=50, verbose_name='NomeFantasia')),
            ],
        ),
    ]
