# Generated by Django 3.2.6 on 2021-08-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_do_emprestimo', models.CharField(max_length=50, verbose_name='Valor do Empréstimo')),
                ('qtd_de_parcelas', models.CharField(max_length=50, verbose_name='Valor do Empréstimo')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
