# Generated by Django 3.2.6 on 2021-08-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_emprestimo_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='qtd_de_parcelas',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='parcelas',
            field=models.CharField(default=1, max_length=50, verbose_name='Parcelas'),
            preserve_default=False,
        ),
    ]
