# Generated by Django 3.2.6 on 2021-08-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0003_auto_20210827_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='contrato',
            field=models.CharField(default=1, max_length=50, verbose_name='Contrato'),
            preserve_default=False,
        ),
    ]
