# Generated by Django 3.2.6 on 2021-08-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0004_emprestimo_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='contrato',
        ),
    ]
