# Generated by Django 3.2.6 on 2021-08-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0006_emprestimo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='contrato',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Contrato'),
        ),
    ]
