# Generated by Django 3.2.6 on 2021-08-12 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dadosbancarios'),
        ('credcoop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecredcoop',
            name='dados_bancarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dadosbancarios', verbose_name='Dados Bancários'),
            preserve_default=False,
        ),
    ]
