# Generated by Django 3.2.6 on 2021-08-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_emprestimo_funcionario'),
        ('credcoop', '0003_clientecredcoop_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientecredcoop',
            name='emprestimo',
        ),
        migrations.AddField(
            model_name='clientecredcoop',
            name='emprestimo',
            field=models.ManyToManyField(to='emprestimo.Emprestimo', verbose_name='Emprestimos'),
        ),
    ]
