# Generated by Django 3.2.6 on 2021-08-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credcoop', '0005_rename_emprestimo_clientecredcoop_emprestimos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientecredcoop',
            old_name='referencia',
            new_name='referencias',
        ),
    ]
