# Generated by Django 3.2.6 on 2021-08-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dadosdaempresa_options'),
        ('credcoop', '0006_rename_referencia_clientecredcoop_referencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientecredcoop',
            name='referencias',
        ),
        migrations.AddField(
            model_name='clientecredcoop',
            name='referencias',
            field=models.ManyToManyField(to='core.Referencia', verbose_name='Referências'),
        ),
    ]
