# Generated by Django 3.2.6 on 2021-08-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dadosdaempresa_options'),
        ('credcoop', '0007_auto_20210827_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientecredcoop',
            name='dados_bancarios',
        ),
        migrations.AddField(
            model_name='clientecredcoop',
            name='dados_bancarios',
            field=models.ManyToManyField(to='core.DadosBancarios', verbose_name='Dados Bancários'),
        ),
    ]
