# Generated by Django 3.2.6 on 2021-09-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_localdetrabalho'),
        ('credcoop', '0008_auto_20210827_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecredcoop',
            name='localDeTrabalho',
            field=models.ManyToManyField(to='core.LocalDeTrabalho', verbose_name='Local de Trabalho'),
        ),
    ]
