# Generated by Django 3.2.6 on 2021-08-12 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dadosbancarios'),
        ('esctop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=50, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=50, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=36, unique=True, verbose_name='CNPJ')),
                ('fundacao', models.DateField(max_length=8, verbose_name='Fundação')),
                ('inscricao_estadual', models.CharField(max_length=50, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(max_length=50, verbose_name='Inscrição Municipal')),
            ],
        ),
        migrations.AlterField(
            model_name='clienteesctop',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dadospessoais', verbose_name='Representante'),
        ),
    ]
