# Generated by Django 3.2.6 on 2021-08-12 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dadosdaempresa_razao_social'),
        ('esctop', '0005_rename_razaosocial_empresa_razao_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fundacao',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='inscricao_estadual',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='inscricao_municipal',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nome_fantasia',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='razao_social',
        ),
        migrations.AddField(
            model_name='empresa',
            name='dados_da_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dadosdaempresa', verbose_name='Dados da empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='representante',
            name='dados_pessoais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dadospessoais', verbose_name='Representante'),
        ),
    ]
