# Generated by Django 3.2.6 on 2021-08-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dadosdaempresa_razao_social'),
        ('esctop', '0009_auto_20210812_0254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DadosDaEmpresa',
            new_name='Empresa',
        ),
    ]
