# Generated by Django 3.2.6 on 2021-08-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esctop', '0012_auto_20210820_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteesctop',
            old_name='dados_da_empresa',
            new_name='dadosDaEmresa',
        ),
    ]
