# Generated by Django 3.2.6 on 2021-08-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esctop', '0013_rename_dados_da_empresa_clienteesctop_dadosdaemresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteesctop',
            old_name='dadosDaEmresa',
            new_name='dados_da_empresa',
        ),
    ]
