# Generated by Django 3.2.6 on 2021-08-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dadosdaempresa_options'),
        ('esctop', '0015_auto_20210820_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteesctop',
            name='representante',
        ),
        migrations.AddField(
            model_name='clienteesctop',
            name='representante',
            field=models.ManyToManyField(to='core.DadosPessoais', verbose_name='Representante'),
        ),
    ]
