# Generated by Django 3.2.6 on 2021-08-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dadosdaempresa_options'),
        ('esctop', '0016_auto_20210820_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contatos', models.ManyToManyField(to='core.Contato', verbose_name='Contatos')),
                ('dados_pessoais', models.ManyToManyField(to='core.DadosPessoais', verbose_name='Representante')),
                ('endereco', models.ManyToManyField(to='core.Endereco', verbose_name='Endereço')),
            ],
        ),
        migrations.AlterField(
            model_name='clienteesctop',
            name='representante',
            field=models.ManyToManyField(to='esctop.Representante', verbose_name='Representante'),
        ),
    ]
