# Generated by Django 3.2.6 on 2021-08-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esctop', '0017_auto_20210820_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representante',
            options={'verbose_name': 'Representante'},
        ),
    ]
