# Generated by Django 3.2.6 on 2021-08-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dadosdaempresa_options'),
        ('esctop', '0018_alter_representante_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante',
            name='dados_pessoais',
        ),
        migrations.AddField(
            model_name='representante',
            name='dados_pessoais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dadospessoais', verbose_name='Representante'),
            preserve_default=False,
        ),
    ]
