# Generated by Django 3.2.6 on 2021-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dadosdaempresa_options'),
        ('esctop', '0021_auto_20210820_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante',
            name='dados_pessoais',
        ),
        migrations.AddField(
            model_name='representante',
            name='dados_pessoais',
            field=models.ManyToManyField(to='core.DadosPessoais', verbose_name='Representante'),
        ),
    ]
