# Generated by Django 3.2.6 on 2021-08-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_dadosdaempresa_options'),
        ('esctop', '0030_auto_20210827_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteesctop',
            name='enderecos',
            field=models.ManyToManyField(to='core.Endereco', verbose_name='Endereços'),
        ),
        migrations.RemoveField(
            model_name='clienteesctop',
            name='fiador',
        ),
        migrations.AddField(
            model_name='clienteesctop',
            name='fiador',
            field=models.ManyToManyField(to='esctop.Fiador', verbose_name='Fiador'),
        ),
        migrations.AlterField(
            model_name='fiador',
            name='dados_bancarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dadosbancarios', verbose_name='Dados Bancários'),
        ),
        migrations.AlterField(
            model_name='fiador',
            name='dados_pessoais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dadospessoais'),
        ),
        migrations.AlterField(
            model_name='fiador',
            name='enderecos',
            field=models.ManyToManyField(to='core.Endereco', verbose_name='Endereço'),
        ),
    ]
