# Generated by Django 3.2.6 on 2021-08-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esctop', '0031_auto_20210827_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representante',
            options={'verbose_name': 'Representante', 'verbose_name_plural': 'Representantes'},
        ),
    ]
