# Generated by Django 3.2.6 on 2021-08-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
        ('core', '0014_alter_dadosdaempresa_options'),
        ('esctop', '0034_alter_clienteesctop_emprestimo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fiador',
            new_name='FiadorEsctop',
        ),
        migrations.AlterModelOptions(
            name='fiadoresctop',
            options={'verbose_name': 'Fiador Esctop', 'verbose_name_plural': 'Fiadores Esctop'},
        ),
        migrations.RemoveField(
            model_name='clienteesctop',
            name='fiador',
        ),
        migrations.AddField(
            model_name='clienteesctop',
            name='fiador_esctop',
            field=models.ManyToManyField(to='esctop.FiadorEsctop', verbose_name='Fiador Esctop'),
        ),
    ]
