# Generated by Django 3.2.6 on 2021-08-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_dadosdaempresa_options'),
        ('esctop', '0035_auto_20210827_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Representante',
            new_name='RepresentanteEsctop',
        ),
        migrations.AlterModelOptions(
            name='representanteesctop',
            options={'verbose_name': 'Representante Esctop', 'verbose_name_plural': 'Representantes Esctop'},
        ),
        migrations.RemoveField(
            model_name='clienteesctop',
            name='representante',
        ),
        migrations.AddField(
            model_name='clienteesctop',
            name='representante_esctop',
            field=models.ManyToManyField(to='esctop.RepresentanteEsctop', verbose_name='Representante Esctop'),
        ),
    ]
