# Generated by Django 3.2.6 on 2021-08-30 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esctop', '0036_auto_20210827_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmprestimoEsctop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_do_emprestimo', models.CharField(max_length=50, verbose_name='Valor do Empréstimo')),
                ('parcelas', models.CharField(max_length=50, verbose_name='Parcelas')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
