# Generated by Django 3.2.6 on 2021-08-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esctop', '0037_emprestimoesctop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteesctop',
            name='emprestimo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esctop.emprestimoesctop', verbose_name='Emprestimos'),
        ),
    ]
