# Generated by Django 3.2.6 on 2021-08-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0003_auto_20210827_0447'),
        ('esctop', '0040_auto_20210830_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteesctop',
            name='emprestimos',
        ),
        migrations.AddField(
            model_name='clienteesctop',
            name='emprestimos',
            field=models.ManyToManyField(to='emprestimo.Emprestimo', verbose_name='Emprestimos'),
        ),
    ]
